version: "3.8"

x-frontend: &frontend
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - /app/node_modules
    - .:/app

services:
  web:
    <<: *frontend
    ports:
      - "3000:3000"
  tests:
    <<: *frontend
    command: ["npm", "run", "test"]
